name: autocheck

on: push

jobs: 
  check: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dep
      run: |
          python -m pip install --upgrade pip
          pip install requests
    - name: check
      run: |
          python test.py
          python ./checkv2.py
      
